title: HPC test
description: Exercise for HPC
instructions: |
    <p>
      testing
    </p>
view_type: access.types.stdasync.acceptFiles
files:
  - field: file1
    name: hpc_test.sh

container:
  image: grading_copy
  mount: exercises/hpc_test
  cmd: /exercise/run.sh

# feedback_template: ./exercises/fibonacci/feedback_template.html